### PR TITLE
Support for `conjugate` and `sympy.I`, for handling complex functions

### PR DESCRIPTION
**Pull request by ipcamit**
It can now handle complex functions containing `sympy.I` constant. In response to #7 .

### CODE REVIEW

**Comment by patrick-kidger** [comment]
Looks good to me! Thanks for the PR.

Can you also add a test for the relevant functionality? And if you can bump the verison number as well then I'll do a new release.

**Comment by ipcamit** [comment]
Added `test_complex` for simple evaluation and conversion checks of complex numbers, as well as evaluation of spherical harmonics using `lambdify`. Also bumped version to `0.1.2`

> Note: The error tolerance for spherical harmonic test is set to `1e-7` as the test file does not use default tensor type as `torch.DoubleTensor`. Therefore internal evals result in limited precision. With default double datatype I get errors to be `9.724027063517389e-16`

**Comment by madagra** [comment]
Thanks @ipcamit for this feature and @patrick-kidger for the great library! To make sure also the `.sympy()` method works with complex expressions, you can include an additional check:

```
def sympy(self, _memodict):
    if issubclass(self._sympy_func, sympy.Float):
        return self._sympy_func(self._value.item())
    elif issubclass(self._sympy_func, sympy.core.numbers.ImaginaryUnit):
        return sympy.I
    elif ...
```

**Comment by ipcamit** [comment]
@madagra Thanks for the suggestion. `sympy()` method can now properly render the equations.

**Comment by patrick-kidger** [comment]
Thanks for the contribution! I've just done a new release.

**Pull request merged**
