### PR TITLE
Add support for constants

### PR DESCRIPTION
**Pull request by casellimarco**
Enables support for all the subclasses of `NumberSymbol`, i.e. `sympy.pi, sympy.E, sympy.GoldenRatio, sympy.TribonacciConstant, sympy.EulerGamma, sympy.Catalan`

### CODE REVIEW

**Comment by patrick-kidger** [comment]
LGTM! Thanks for the contibution.

**Comment by casellimarco** [comment]
Thanks @patrick-kidger for this tool, it's really useful! Any plan about making a new release soon? If possible, I would like to install the latest version from pypi

**Comment by patrick-kidger** [comment]
Sure thing! I've just bumped the version and done a release.

**Comment by casellimarco** [comment]
Fantastic, many thanks!

**Pull request merged**
